[package]
name = "citrus"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.108.1"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.20.2"
