name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Release
      run: |
        gh release create ${{ env.RELEASE_ID }} release.tar.xz
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
